"""Clean QODEX architecture - no user dependencies

Revision ID: 2e8f053488b9
Revises: 16e292816c22
Create Date: 2025-10-25 19:08:49.834310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e8f053488b9'
down_revision: Union[str, None] = '16e292816c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('repositories', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'READY', 'FAILED', name='repositorystatus'),
               type_=sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='repositorystatusenum'),
               existing_nullable=True)
    op.create_unique_constraint(None, 'repositories', ['github_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='unique')
    op.alter_column('repositories', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='repositorystatusenum'),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'READY', 'FAILED', name='repositorystatus'),
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
